---
title: "LMM_Power"
output: html_document
date: '2022-08-27'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}
if (!require(tidyverse)) {library(tidyverse)}
if (!require(faux)) {library(faux)}
if (!require(mixedpower)) {library(mixedpower)}
set.seed(2022)
```

假设我们进行一个语音感知研究，自变量是听觉模式（modality）以及背景噪音（SNR），听觉模式有两个水平：纯音频条件（Audio-only）、视听条件（Audiovisual）；背景噪音有简单（Easy）、困难（Hard）两个水平。因变量是反应时。我们使用`library(faux)`进行模拟实验数据的生成。

```{r pressure, echo=FALSE}
subj_n <- 10   # 总被试量
trial_n <- 5  # 每种刺激呈现的次数 *4 一个被试总的trials是20次

# 固定效应
b0 <- 200     # 截距 (所有条件的均值)
b1 <- 56      # 听觉模式的固定效应
b2 <- 92      # 背景噪音的固定效应
b3 <- -10     # 听觉模式与背景噪音的交互作用

# 随机效应
u0s <- 34    # 被试的随机截距
u1s <- 200  # 被试的听觉模式随机斜率 
u2s <- 10     # 被试的背景噪音模式随机斜率 

# 误差项
sigma <- 70
```

```{r}
#生成假定实验的条件的数据矩阵
df_simu <- add_random(subj = subj_n) %>%
  # 添加听觉模式类型的信息（被试内）
  add_within("subj", modality = c("Audio-only","Audiovisual"), SNR = c("Easy","Hard")) %>%
  # 每种刺激会呈现10次
  add_random(trial = trial_n) %>%
  # 视听模式的编码：纯音频条件=0；视听条件=1
  add_contrast("modality", "treatment", colnames = "modality_code") %>%
  # 背景噪音的编码：简单0；困难1
  add_contrast("SNR", "treatment",colnames = "SNR_code") %>% 
  # 添加基于被试的随机截距和斜率
  add_ranef("subj", u0s = u0s, u1s =u1s , .cors=0.5) %>% 
  add_ranef("subj", u0s = u0s, u2s =u2s , .cors=0.5) %>%
  # 添加观察值的误差项
  add_ranef(sigma = sigma) %>% 
  # 最后根据设置的固定效应和随机效应参数值，生成因变量。
  mutate(RT = (b0+u0s) +         # 截距
           (b1+u1s) * modality_code + # 视听模式的斜率
           (b2+u2s) * SNR_code +      # 背景噪音的斜率
            b3 * modality_code * SNR_code +   
           sigma)         #误差项  

head(df_simu,10) #查看生成的数据矩阵
```

```{r}
df_simu <- df_simu %>% 
  select(subj, stim, modality, SNR, RT) # 去除冗余的信息

head(df_simu, 5)#查看数据结构
```



```{r model setup}
# 编码
df_simu$modality <- ifelse(
    df_simu$modality == "Audio-only", 0, 1)
df_simu$SNR <- ifelse(
    df_simu$SNR == "Easy", 0, 1)
library(stringr)
df_simu$subj<-as.numeric(str_sub(df_simu$subj,2,3))
#df_simu$stim<-as.numeric(str_sub(df_simu$stim,2,3))

## 模型
model_1<- lmer(RT ~ 1 + modality * SNR +
                 (1 + modality + SNR|subj), 
                  data = df_simu)
summary(model_1)
```

```{r power analysis}
model <- model_1 # which model do we want to simulate power for?
data <- df_simu # data used to fit the model
fixed_effects <- c("modality", "SNR") # all fixed effects specified in model
simvar <- "subj" # which random effect do we want to vary in the simulation?
steps <- c(20,30,40) # which sample sizes do we want to look at?
critical_value <- 2 # which t/z value do we want to use to test for significance?
n_sim <- 1000 # how many single simulations should be used to estimate power?

model_1_power <- mixedpower(model = model, data = data,
                        fixed_effects = fixed_effects,
                        simvar = simvar, steps = steps,
                        critical_value = critical_value, n_sim = n_sim)
model_1_power 
```
```{r power analysis SESOI}
model <- model_1 # which model do we want to simulate power for?
data <- df_simu # data used to fit the model
fixed_effects <- c("modality", "SNR") # all fixed effects specified in model
simvar <- "subj" # which random effect do we want to vary in the simulation?
steps <- c(15,20,25) # which sample sizes do we want to look at?
critical_value <- 2 # which t/z value do we want to use to test for significance?
n_sim <- 1000 # how many single simulations should be used to estimate power?
SESOI <- c(38, 63, 92, -10) # specify SESOI

model_2_power <- mixedpower(model = model, data = data,
                        fixed_effects = fixed_effects,
                        simvar = simvar, steps = steps,
                        critical_value = critical_value, n_sim = n_sim,
                        SESOI = SESOI, databased = T)
model_2_power 
multiplotPower(model_2_power)
```



